### ISSUE TITLE
Migrate identity keystore to lightweight 

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#2134]
On node bootstrap check if current identity is heavyweight, if it is re-create keystore with lightweight scrypt.

**Comment by anjmao** [comment]
@Waldz If you will work on this please assign it yourself. We can't release a new version before this is solved.

**Comment by zolia** [comment]
#2169 does not fix this exact issue. We still have all old identities being unlocked as heavyweight. Probably not as critical now.

**Comment by chompomonim** [comment]
I think we already are using lightweight keystore.
