### ISSUE TITLE
Test node and apps for Testnet 2.0

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2844]
We're going to launch new TestNet soon. In terms to have smooth migration process we would need to test it heavely before starting migration of all nodes and consumers.

**Node testing scenarios:**
- [ ] Install node (provider) from .deb package and do on-boarding using WebUI.
    - on RPi
    - on macBook
    - on Linux desktop
- [x] Install node (provider) from .deb on Linux server (in datacenter) and setup it using CLI.
- [x] Install Node (provider) in docker and setup it via CLI.
- [x] Test claim MMN via CLI.
- [x] Test note registration using referral code.
- [ ] Upgrade node from v0.39.x to v0.40+ (from testnet to testnet2). Node should maintain same identity and auto-reigster it into testnet2 registry.

**Apps testing:**
While testing any of our app, you should try filtering exit node list via different params. Then trying to connect to a couple of different nodes and maintain connection for at least 40 minutes. Check if your tokens are calculated and that your connection is stable. Try changing settings (e.g. changing DNS) and see it all still works. Try in-app chat and report issue features.

- [x]  Install newest android app (v0.40+) via .apk.
- [x]  Install newest android app (v0.40+) from Google Play (only for participants in betatesting program).
- [ ]  Install windows desktop app(download v3.2+ from GitHub).
- [ ]  Install macOS desktop app (download v3.2+ from GitHub).
- [x]  Test consumer mode in CLI on Linux or macOS.

**Testing topups:**
- [ ] Test topups using referral codes.
- [ ] Test topup by sending test tokens (MYSTT) into consumer payment channel address.
- [ ] Test topup by using payment processor integration (e.g. using Litecoin or Ethers).

NOTES:
** ping @chompomonim to get some test MYSTT for tests.
** ping @chompomonim, @tadaskay or @vkuznecovas to get referral code.

**Comment by etherunit** [comment]
- Test claim MMN via CLI.
Blocked by https://github.com/mysteriumnetwork/my.mysterium.network/issues/47
» ```
mmn 0HeOP7t8WmjK5zLewRKY69nSqjtvozKr6N4peFLV
2020-11-24T12:55:41.575 DBG config/config.go:196                     > Returning default value mmn.web-address:https://testnet2.mysterium.network/
2020-11-24T12:55:41.617 ERR tequilapi/client/http_client.go:123      >  error="server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/mmn/api-key). Possible error: Post https://testnet2.mysterium.network/api/v1/node: remote error: tls: internal error"
```

**Comment by vkuznecovas** [comment]
These will not be testable: 
 Test topups using referral codes. -> referrals only work on l2, no l2 right now, so you'll end up getting errors rejecting your tokens.
 Test topup by sending test tokens (MYSTT) into consumer payment channel address. -> this is not possible, as registrations are now funded by transactor.

**Comment by soffokl** [comment]
WebUI copy address button does nothing:
![image](https://user-images.githubusercontent.com/8612618/100705291-28c34780-33d1-11eb-8ead-3abe03bd14aa.png)

**Comment by etherunit** [comment]
`myst cli`
I could claim my node into testnet2 dashboard by using `mmn <token>`
<img width="882" alt="Screenshot 2020-12-10 at 09 36 46" src="https://user-images.githubusercontent.com/60128746/101735953-55f7b000-3acb-11eb-8816-f13e657f9554.png">

but when I go to NodeUI I should sync node to MMN too. It then registers a new node identity?
<img width="939" alt="Screenshot 2020-12-10 at 09 36 58" src="https://user-images.githubusercontent.com/60128746/101735980-60b24500-3acb-11eb-8632-ea2fb9c1480f.png">

**Comment by chompomonim** [comment]
Issues I have found during test of `0.40.6-pre`:

- [ ] Can't see node version in WebUI
- [ ] Reconnect doesn't work on CLI and Android
- [ ] Connects to node only after second attempt (via android app)
- [ ] User should see MYSTT in CLI (not MYST)

```
$ ./myst account info
[SECTION] General account information:
[INFO] Using identity: 0x099cbd053ce5f720d69ce6730d7c4d453ce9a5e3
[INFO] Registration Status: Registered
[INFO] Channel address: 0x1B4216269347235Be4A6bc074De773E1C862c4cb
[INFO] Balance: 5.000000MYST
```

- [ ] Can't claim node into MMN via WebUI

Getting such message in Browser console.
```
VM33:1 POST http://128.199.33.128:4449/tequilapi/mmn/api-key 500 (Internal Server Error)
main.690b41d8.chunk.js:1 Uncaught (in promise) TypeError: Cannot read property 'api_key' of undefined
    at main.690b41d8.chunk.js:1
    at main.690b41d8.chunk.js:1
```

I would also expect link into instructions how to do that.
<img width="1424" alt="Screenshot 2020-12-14 at 17 48 50" src="https://user-images.githubusercontent.com/153896/102102580-a9079500-3e34-11eb-8c07-4df49dc127e0.png">

Also tried to do that via CLI, got SUCCESS message (`[SUCCESS] MMN API key configured.`) but still don't see node in MMN dashboard.

**Comment by tomasmik** [comment]
> User should see MYSTT in CLI (not MYST)
This and every other place which has currency in it, should be fixed with these PR's which are merged:
* https://github.com/mysteriumnetwork/node/pull/2924
* https://github.com/mysteriumnetwork/node/pull/2925

These are not included in the version you've tested.

**Comment by chompomonim** [comment]
Can't connect using `myst connection` command.

```
$ ./myst connection 0x464e64b89a08de0c1eb0442ea4d65ff80be87671
No help topic for '0x464e64b89a08de0c1eb0442ea4d65ff80be87671'
```

```
$ ./myst connection up 0x464e64b89a08de0c1eb0442ea4d65ff80be87671
[WARNING] ProviderID must be specified
```

**Comment by chompomonim** [comment]
Still getting `NAT status Not Finished` message while running datacenter node.

![Screenshot 2020-12-15 at 06 57 48](https://user-images.githubusercontent.com/153896/102173080-ef93d880-3ea2-11eb-90ac-47f8aa734c2c.png)
