### ISSUE TITLE
Your identity is being registered, please be patient..

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3003]
Provider: 0xa84a29a32bb38c2694a1fe35a0c691a662bd8d30;
Migrated node from V1 to V2 network but stuck on identity registration screen;
<img width="843" alt="Screenshot 2021-01-18 at 14 13 31" src="https://user-images.githubusercontent.com/60128746/104914151-5e2eef00-5997-11eb-8520-45a7b3061de9.png">
<img width="1456" alt="Screenshot 2021-01-18 at 14 16 05" src="https://user-images.githubusercontent.com/60128746/104914378-b960e180-5997-11eb-9d0c-d8b3d00a7a31.png">

<img width="1299" alt="Screenshot 2021-01-18 at 14 15 35" src="https://user-images.githubusercontent.com/60128746/104914334-a8b06b80-5997-11eb-9a0b-fcedc1e34396.png">
Node logs: https://testnet2.mysterium.network/admin/issues/download/1628

**Comment by vkuznecovas** [comment]
Identity was registered, see 
https://testnet2-transactor.mysterium.network/api/v1/identity/0xa84a29a32bb38c2694a1fe35a0c691a662bd8d30/status

Registration tx:
http://goerli.etherscan.io/tx/0x1e47cc2ab9ece36d6cf910373cedc114d997a13918dad415e33cedf47b4824a5

Seems like the bug is related to the reporting of the status.

**Comment by etherunit** [comment]
Adding another provider facing registration reporting issues.
0x485a502e4c08ae22e0bfac282453941a2b72cb29

```
Jan 16 16:29:44 raspberrypi myst[2268]: 2021-01-16T16:29:44.378 INF identity/registry/provider_registrar.go:183 > Provider "0x485a502e4c08ae22e0bfac282453941a2b72cb29" not registere
d on BC, will check if elgible for auto-registration
Jan 16 16:29:44 raspberrypi myst[2268]: 2021-01-16T16:29:44.582 DBG config/config.go:196 > Returning default value chain-id:5
Jan 16 16:29:44 raspberrypi myst[2268]: 2021-01-16T16:29:44.713 ERR identity/registry/provider_registrar.go:218 > Registration failed for provider "0x485a502e4c08ae22e0bfac282453941
a2b72cb29" error="server response invalid: 429 Too Many Requests (https://testnet2-transactor.mysterium.network/api/v1/identity/register)Limit exceeded"
Jan 16 16:29:44 raspberrypi myst[2268]: 2021-01-16T16:29:44.716 ERR identity/registry/provider_registrar.go:149 > Could not complete registration for provider "0x485a502e4c08ae22e0b
fac282453941a2b72cb29". Will retry. Retry 1 of 10 error="could not register identity on BC: server response invalid: 429 Too Many Requests (https://testnet2-transactor.mysterium.net
work/api/v1/identity/register)Limit exceeded" stack=[{"func":"(*ProviderRegistrar).registerIdentity","line":"219","source":"provider_registrar.go"},{"func":"(*ProviderRegistrar).han
dleEvent","line":"184","source":"provider_registrar.go"},{"func":"(*ProviderRegistrar).handleEventWithRetries","line":"144","source":"provider_registrar.go"},{"func":"(*ProviderRegi
strar).start","line":"239","source":"provider_registrar.go"},{"func":"(*ProviderRegistrar).handleNodeStartupEvents","line":"110","source":"provider_registrar.go"},{"func":"Value.cal
l","line":"460","source":"value.go"},{"func":"Value.Call","line":"321","source":"value.go"},{"func":"(*EventBus).doPublish","line":"158","source":"event_bus.go"},{"func":"(*EventBus
).doPublishAsync","line":"166","source":"event_bus.go"},{"func":"goexit","line":"868","source":"asm_arm.s"}]
```

**Comment by masterdot** [comment]
0xba22f43595d4c6c6ccc4090298b86b41b758d07f

**Comment by scysys** [comment]
Same here after upgrade from 0.39 to 0.41. 

> Your identity is being registered, please be patient..

Gui message is never ending. But node is sucessfully registered.

**Comment by chompomonim** [comment]
@mdomasevicius could you look deeper at this issue? It seems that it is some bug in NodeUI.

@scysys have you tried to restart node? Are you still getting this issue?

**Comment by si458** [comment]
@chompomonim i too am getting this issue,

already reported to @etherunit

my node is 0x485a502e4c08ae22e0bfac282453941a2b72cb29

A reboot of my pi makes no difference

**Comment by mdomasevicius** [comment]
Seems that after non 2xx registration request identity status in bolt is never updated. 

https://github.com/mysteriumnetwork/node/pull/3026 - should re-fetch status from blockchain if it was persisted `InProgress`

**Comment by Data-Gremlin** [comment]
UI displaying same "Your identity is being registered, please be patient " overlay. Node showing as offline via main account . 
Device rebooted with no change. 
Mysterium notified. @0700 on 21.01.2021

**Comment by Data-Gremlin** [comment]
@chompomonim I have rebooted the node a few times now and are issued a new IP.

Mine is still showing as Offline

**Comment by chompomonim** [comment]
The problem should be fixed with next release `0.41.2`. Now it is in release candidate stage (https://github.com/mysteriumnetwork/node/releases/tag/0.41.2-rc0), should be released today or tomorrow.

**Comment by Data-Gremlin** [comment]
@chompomonim I've just checked and still not available so will recheck in the morning.

**Comment by Data-Gremlin** [comment]
@chompomonim I've just checked and still not available so will recheck in the morning.  

Mine is saying up to date on Ver 0.41 

Running on RP4

**Comment by Data-Gremlin** [comment]
@chompomonim I have my RP4 shh open what do I need to type to get the newest update please. 

I've tried. 

Sudo apt-get update && sudo apt-get upgrade myst

But still not working.

**Comment by chompomonim** [comment]
@Data-Gremlin you should change repository to `'http://ppa.launchpad.net/mysteriumnetwork/node-/ubuntu` in your apt.sources.

**Comment by Data-Gremlin** [comment]
@chompomonim added what you suggested to my sources.list but keep getting this.

Have I added it wrong? Or is as informed 403 Forbidden. 

myst@raspberrypi:~ $ sudo apt-get update && sudo apt-get upgrade myst
Err:1 http://ppa.launchpad.net/mysteriumnetwork/node-/ubuntu buster InRelease
  403  Forbidden [IP: 91.189.95.85 80]
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Ign:4 http://ppa.launchpad.net/mysteriumnetwork/node-testnet2/ubuntu focal InRelease
Hit:5 http://deb.debian.org/debian buster-backports InRelease
Err:6 http://ppa.launchpad.net/mysteriumnetwork/node-testnet2/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Hit:7 http://deb.debian.org/debian unstable InRelease
Reading package lists... Done
E: Failed to fetch http://ppa.launchpad.net/mysteriumnetwork/node-/ubuntu/dists/buster/InRelease  403  Forbidden [IP: 91.189.95.85 80]
E: The repository 'http://ppa.launchpad.net/mysteriumnetwork/node-/ubuntu buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/mysteriumnetwork/node-testnet2/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by scysys** [comment]
> @mdomasevicius could you look deeper at this issue? It seems that it is some bug in NodeUI.
> 
> @scysys have you tried to restart node? Are you still getting this issue?

@chompomonim Yes. This message was never gone. After restart and reboot this message is there. I just reinstalled. It´s fast and solved the error.

**Comment by Data-Gremlin** [comment]
Can anyone help please. Really want to get working again

**Comment by masterdot** [comment]
> Can anyone help please. Really want to get working again

Your repository link is wrong, should be 
http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu

yours is http://ppa.launchpad.net/mysteriumnetwork/**node-**/ubuntu/dists/buster/InRelease

**Comment by si458** [comment]
@Data-Gremlin 
make sure `/etc/apt/sources.list.d/mysterium.list` had the following inside
`deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal main`
then `apt update` and `apt upgrade` it should auto-upgrade the myst package

just upgraded my pi and now web-panel works perfectly, same with the registration!

**Comment by masterdot** [comment]
Same here, fixed for me

**Comment by Data-Gremlin** [comment]
@masterdot I now have it working and have my node transferred. However all my previous transactions and earning haven't transferred over?

**Comment by masterdot** [comment]
@Data-Gremlin  Same here. @chompomonim told me that the previous earnings are on testnet1 and are only transferable, if they exceed the minimum amount. Testnet2 earns for itself.

**Comment by chompomonim** [comment]
Earning on testnet1 stays on testnet1. Testnet2 is completely separate network. Anyway, discussion about earnings is out of context of this issue.

With release of `0.41.2` this issues should be already fixed. Closing it.

**Comment by Data-Gremlin** [comment]
@si458 quick question out of context but when mysterium is on my network does VPN and any other protection stop them gaining access to my Lan ?

**Comment by si458** [comment]
@Data-Gremlin the only thing i have spotted is when i connect to my node from my tablet (using 4g)

i cant access anything on my home network using any ports as expected

HOWEVER if i goto the node ip and a port, then that is accessible

for example i ran a pi node but then installed sonarr or apache on the pi, i was able to access those no problem via the mysterium network

you get the node ip when you look at ur routing table and see what the default gateway is after u connect to your node

**Comment by si458** [comment]
@chompomonim my node has deregistered and wont register again now?

```
Jan 25 18:29:50 raspberrypi myst[1258]: #033[90m2021-01-25T18:29:50.494#033[0m #033[1m#033[31mERR#033[0m#033[0m #033[1mcmd/mysterium_node/mysterium_node.go:68 #033[0m#033[36m >#033
[0m Failed to execute command:  #033[31merror=#033[0m#033[31m"could not get hermes url: daily request count exceeded, request rate limited"#033[0m
```

**Comment by haimo5** [comment]
I have the same problem with your latest docker version.

**Comment by smmsadrnezh** [comment]
I have this problem with the latest docker version.

**Comment by chompomonim** [comment]
@smmsadrnezh this should be caused be temporary problems by our meta transactions delayer and growing even goearli testnet becoming full.

**Comment by vishawsingh** [comment]
I have it for last 20 hours or so and its not going away. On my Nodes Network I can see this machine has been registered but sitting offline with status : Last Seen Never.

![image](https://user-images.githubusercontent.com/94092788/151712738-d6f2b1c4-6437-407e-9a76-928a97d806fc.png)
