### ISSUE TITLE
Test Fail and not showing in app after update new release 0.48.0

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3546]
**Describe the bug**
0x641cb8019932b0fc112eeb1c265a4e93811c9086 - Status test failed ever since stopped having sessions 2 days ago

**To Reproduce**
Followed documentation instructions you gave Raspberry Pi update.

"MMN shows "test failed", and node is not listed in Myst client.
I have updated to 0.47.3 and then to 0.48.0, but nothing has changed.
By checking the status of the node, service seems to be ok.
Port-forwarding on the router is correctly set, and I did not change anything there."

**Environment (please complete the following information):**
OS:Raspbian GNU/Linux 10 (buster)
Architecture:linux/arm
Node version:0.48.0

**Additional context**
[putty.log](https://github.com/mysteriumnetwork/node/files/6708635/putty.log)

**Comment by soffokl** [comment]
@isaackielma does this node has any non default configuration applied? 
I see it's trying to use UPnP port mapping, but router has local IP too, so there several NAT levels exist in his network. 
It should use NAT hole punching to pass this limitation, but based on logs it looks like it's not used. Is it explicitly disabled? 

I recommend to remove all non default configuration and try to use NAT hole punching for that node to make it work.

**Comment by isaackielma** [comment]
@soffokl  uPnP / NAT Traversal / Hole punching has never worked in his environment for some reason.
Provider has disabled it by following instructions on "troubleshooting" section of the documentation, and then forwarded the ports on the router.
This configuration has been working fine until the 22nd of June.

**Comment by soffokl** [comment]
I see he reverted NAT hole punching and it online now and working. 
We are constantly improving the connection possibilities. If it was not working a long time ago, it could be fixed now and work again.

**Comment by christopherchild** [comment]
This is very similar to what I am experiencing with my node.

All was working correctly, up until I updated to 0.47.x. After this update I now see "Test failed" in the status. I have updated to 0.48 and no change.

Nothing has changed on my end in terms of the networking and I have never setup any port forwarding and changed anything with regards to this.

Have to help troubleshoot.

**Comment by soffokl** [comment]
@christopherchild could you share your node ID?

**Comment by 03c** [comment]
@soffokl sorry for the delay.

My node ID: 0x4baa7f1864851266d8df12c0e8a22e20f0fc29f2

You can see from the below screenshot exactly what I am looking at. As you can see, there have been no connections from around the 21st (when I initially updated to 0.47.x).

I am happy to change settings on both my node and my router to diagnose the problem.

![image](https://user-images.githubusercontent.com/996720/123943414-0a87ef00-d994-11eb-9af8-24947cca64df.png)

**Comment by soffokl** [comment]
@03c hey, we just released a 0.50.1 version with fixes. Could you try to update it? I think it could help to resolve the problem with your node. 
Please let me know once you update, I'll check it again.

**Comment by 03c** [comment]
@soffokl done, showing 0.50.1 in the UI. Not sure how long it would take MMN to update. But it's still showing "Test failed" and also saying "No services found".

**Comment by 03c** [comment]
Services are now showing in MMN.

**Comment by soffokl** [comment]
@03c it's online now, seems to work fine. Thanks for your fast assistance.

**Comment by 03c** [comment]
Looking better :)

![image](https://user-images.githubusercontent.com/996720/123972368-b0e2ed00-d9b2-11eb-9491-4f454fec1e4a.png)

Thanks very much!

**Comment by lollapalooza1973** [comment]
I'm still having issues.
Node has updated to 0.50.1, but nothing has changed.
MMN shows "test failed".

I'm using port-forwarding, because NAT traversal does not work in my environment.
Here's the options in /etc/default/mysterium-node
DAEMON_OPTS="--p2p.listen.ports=51820:52075 --experiment-natpunching=false --keystore.lightweight"
SERVICE_OPTS="--wireguard.listen.ports=52820:53075 wireguard"

Above ports are forwarded on the router.
I can send the node logs if needed.

**Comment by soffokl** [comment]
@lollapalooza1973 Could you share your node ID?

**Comment by lollapalooza1973** [comment]
@soffokl here it is: 0x641cb8019932b0fc112eeb1c265a4e93811c9086

**Comment by soffokl** [comment]
@lollapalooza1973 I see it was working when nat hole punching was active a few days ago. 
And another note, you have prices a bit higher than allowed, so the monitoring agent does not check your node. 
Could you please adjust pricing and enable nat hole punching? I'll check your node again after it.

**Comment by lollapalooza1973** [comment]
@soffokl 
I have enabled NAT traversal / hole punching, and also lowered the prices. I still have the same issue.
Here's the current options of /etc/default/mysterium-node
DAEMON_OPTS="--nat-port-mapping=false --keystore.lightweight"
SERVICE_OPTS="openvpn,wireguard"

**Comment by lollapalooza1973** [comment]
@soffokl Node is updated to 0.51.0, but nothing has changed.

**Comment by lollapalooza1973** [comment]
@soffokl I think I found what is the issue.
In my LAN there's a device in the DMZ (and I need it there).
If I disable the DMZ, NAT traversal / hole punching works fine (I can establish a connection to my node).

WHen I enable the DMZ, NAT traversal / hole punching does not work.

I tried also to leave DMZ disabled, and use "port forwarding" options in /etc/default/mysterium-node, together with relative ports forwarded in the router, but I can't establish any connection to my node.

Anyway, with all the tests I did, the status in MMN always shows "test failed".

**Comment by soffokl** [comment]
@lollapalooza1973 your price per hour still looks high.
These are the max prices that NodeUI allows users to set:
![image](https://user-images.githubusercontent.com/8612618/124411890-38dc4480-dd6f-11eb-8324-f8c459eba158.png)

**Comment by lollapalooza1973** [comment]
@soffokl you're right.
But in the Myst client app I see that just a few people follows that rule. 
Furthermore, the app's default filter is set to 0.0054 Myst per hour (and max is 0.0108), which is far higher that 0.00018
![image](https://user-images.githubusercontent.com/34000198/124424958-2dd1e600-dd68-11eb-892a-070f1f2da82a.png)

And in any case this does not fix the issue I have with the DMZ/port-forwarding.
How do I make the node work with the port-forwarding?

**Comment by lollapalooza1973** [comment]
@soffokl 
I moved the slider to the maximum and saved, and now I see status "online" on MMN.
Anyway, I still can't run the node with port-forwarding. How do I fix this?

**Comment by soffokl** [comment]
I cannot say what it's not working as expected. It very depends on the router and configuration. 
For the mysterium node port needs to be forwarded and working, if something is blocking it node will not receive packets.

**Comment by lollapalooza1973** [comment]
@soffokl I can tell that it was correctly working until some days ago (and I did not change the router).
I can re-enable port-forwarding on the node (and on the router), and provide the logs for you to check.
How do I send the logs?

**Comment by soffokl** [comment]
@lollapalooza1973 Report issue from the NodeUI, mention me as `@soffokl` in the text.

**Comment by lollapalooza1973** [comment]
@soffokl done... I used the "report issue" button.
Thanks.

**Comment by lollapalooza1973** [comment]
@soffokl kindly let me know if you need something else.
I'll cross fingers for the issue to be fixed. Thank you.

**Comment by soffokl** [comment]
@lollapalooza1973 sorry missed the thing from your port forwarding screenshot. You have MYST P2P for `TCP` only, but `UDP` is required for the connection.

**Comment by lollapalooza1973** [comment]
@soffokl Thanks! It's working now!
