### ISSUE TITLE
[android] proposals fetching very slow on Android

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4421]
**Describe the bug**
It takes 30-60 seconds to fetch proposals on Android.

Yet it takes 2-3 seconds to fetch on desktop apps.

**Environment (please complete the following information):**
 - Node version: 1.0.7
 - OS: Android

**Comment by etherunit** [comment]
We had an issue with our load balancers which hit limit of its capacity. Team rescaled it and problem was resolved. Is there still a delay in fetching service proposals @cvl?

**Comment by cvl** [comment]
Yes, this problem is present for a long time (reported first time like 1-2 years ago).
Still present today after rescaling. Something wrong with Android implementation in particular.

**Comment by cvl** [comment]
x

**Comment by Donatas-MN** [comment]
It's probably due to slower internet connection and bigger proposal list size (growing number of nodes). There is an improvement planned to limit proposal list, so download time would be reduced.

**Comment by cvl** [comment]
The problem is the current implementation of how nodes lists is received.

Proposals list is fetched pretty fast (~5s), yet parsing back and forth from json to binary then back to json in Android app takes almost a minute.

I'd suggest to move proposals list fetching to Android app instead of having it in node.

Putting limits to proposals list is a) bad idea, as it further centralizes Mysterium network b) doesn't improve a speed much (even having 300 proposals takes 20 seconds or so).

**Comment by Snawoot** [comment]
@cvl That's okay, but can you answer question I've asked?

**Comment by Snawoot** [comment]
Looking at that code I see that it uses Klaxon library for JSON parsing which has [known performance issue](https://github.com/cbeust/klaxon/issues/154), which is [caused by Kotlin runtime itself](https://youtrack.jetbrains.com/issue/KT-33760#comment=27-3721332). So regardless of origin of proposals (node or app fetches it on its own), it will be slow to parse JSON with this parser if this issue is the root cause.

I'll escalate this to mobile dev team.

**Comment by cvl** [comment]
> @cvl That's okay, but can you answer question I've asked?

Answered with the first sentence "All the versions are affected."

The linked code is in master, this part didn't change since inception.

> I'll escalate this to mobile dev team.

Thank you.

**Comment by Donatas-MN** [comment]
JSON parser has been replaced with Moshi.
