### ISSUE TITLE
identity not found (path="identities/0x/balance/refresh")

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4846]
It's happening at the time when UI is opened. After refreshing the page it disappear.

![Screenshot 2022-03-06 at 10 10 27](https://user-images.githubusercontent.com/60128746/156914870-eae6f623-a6d0-4303-bf9d-1cdab13013d9.png)

Node version: mainnet (1.4.0-b32febb0)
NodeUI version: 1.7.3
OS: Docker (Alpine)

**Comment by Donatas-MN** [comment]
@lusine-h could you try to reproduce this one?

**Comment by tomasmik** [comment]
I get the same. It literally only requires me to open the node-ui.

**Comment by Donatas-MN** [comment]
Yeah, got the same as well.

**Comment by mdomasevicius** [comment]
This should be fixed; there was a race condition that I fixed with another task.

**Comment by lusine-h** [comment]
still appears for me:
![image](https://user-images.githubusercontent.com/60058956/163955684-50590de9-47ce-4f21-ac58-b31f1678a5ee.png)

**Comment by lusine-h** [comment]
I get errors like this
![image](https://user-images.githubusercontent.com/60058956/170688894-c682b08a-0c1e-4a87-8a2b-fa19beb47247.png)
