### ISSUE TITLE
0.19 MYST payout for 12 hours session, 228.08GB transfer?

### ISSUE THREAD

**Issue by astronyu** [mysteriumnetwork/node#4900]
**Describe the bug**
A session lasts for almost 12 hours consumed 228.08GB of data and rewarded with 0.19 MYST

**Expected behavior**
Would expect the rewards would match current pricing
Price per hour 0.0006373 MYST
Price per GB 0.1068289 MYST

**Screenshots**
![Screenshot 2022-03-20 124506](https://user-images.githubusercontent.com/3217740/159148671-f4f41574-1ab0-43b4-b7df-dcff48da211b.png)
![Screenshot 2022-03-20 123857](https://user-images.githubusercontent.com/3217740/159148761-79563d47-1cfc-4954-88ff-db974c04188f.png)

**Environment (please complete the following information):**
 - Node version: mainnet (1.4.10-743a8319)
 - NodeUI version: 1.8.0
 - OS: Windows
 - Desktop app version (if applicable): 1.0.27
 - Your identity (if applicable): 0xabd3f060dd1d4a342bdb3b7eca5b232cd159de95

**Additional context**
I was online when the session started and monitored it for a couple of hours. At some point there was another session started but ended sooner while this one kept going. Went to bed and later found out the rewards was a not as per current pricing. How does earning calculation works exactly??

**Comment by mrtnd** [comment]
I have the exact same problem. Session lasted more than 2 days. More than 500gb were transferred and the rewards are 0,39. 
![Mysterium Node UI](https://user-images.githubusercontent.com/44461993/159150546-81572742-b1c7-405c-9e43-288f7b0fdb89.png)

can that be fixed so that rewards are shown correctly or are the rewards just gone now ?

**Comment by Guillembonet** [comment]
@mrtnd this is a known bug and should be fixed in 1.4.9

@astronyu can you submit logs if this bug happened in a version outside the 1.4.3-1.4.9 range? you can use the report bug button in node ui for that. Thanks!

**Comment by mrtnd** [comment]
@Guillembonet just updated to: 
Node version: mainnet (1.4.10-743a8319)
NodeUI version: 1.8.0

and still shows: 
0.3943101 MYST  515.41 GB

does that mean that the rewards are gone?

**Comment by Guillembonet** [comment]
@mrtnd yes, sadly that session calculations were wrong and the invoice sent to the consumer was less than it should

**Comment by mrtnd** [comment]
> @mrtnd yes, sadly that session calculations were wrong and the invoice sent to the consumer was less than it should

@Guillembonet all right, thanks for the quick reply.

**Comment by astronyu** [comment]
Can a dev confirm what is the status of the loss earning due to this glitch? Will the node operator get reimbursed?

**Comment by astronyu** [comment]
> 

I've sent a bug report through the bug button just now.

**Comment by astronyu** [comment]
> @mrtnd this is a known bug and should be fixed in 1.4.9
> 
> @astronyu can you submit logs if this bug happened in a version outside the 1.4.3-1.4.9 range? you can use the report bug button in node ui for that. Thanks!

I've sent a bug report through the bug button just now.

**Comment by etherunit** [comment]
@astronyu Yes, please provide the sessiond id + node identity. We will manually cover all previous losses caused by this problem.

**Comment by astronyu** [comment]
> @astronyu Yes, please provide the sessiond id + node identity. We will manually cover all previous losses caused by this problem.

Are those required information already in the report above or I need to send some logs to someone via email? Btw, I've DM'ed Adine on discord with the screenshot.

**Comment by mrtnd** [comment]
> > @astronyu Yes, please provide the sessiond id + node identity. We will manually cover all previous losses caused by this problem.
> 
> Are those required information already in the report above or I need to send some logs to someone via email? Btw, I've DM'ed Adine on discord with the screenshot.

Well count me in. More than 500GB of traffic and only 0.3943101 MYST (in my case) is way too less to ignore. And I have the same question. Who do we contact and how?

**Comment by astronyu** [comment]
> > > @astronyu Yes, please provide the sessiond id + node identity. We will manually cover all previous losses caused by this problem.
> > 
> > 
> > Are those required information already in the report above or I need to send some logs to someone via email? Btw, I've DM'ed Adine on discord with the screenshot.
> 
> Well count me in. More than 500GB of traffic and only 0.3943101 MYST (in my case) is way too less to ignore. And I have the same question. Who do we contact and how?

I believe you need to send them node identity and session id for reimbursement.

**Comment by mrtnd** [comment]
> @astronyu Yes, please provide the sessiond id + node identity. We will manually cover all previous losses caused by this problem.

These are mine: 
Node identity: 0x40319c8aff15152adaba189775f5250c3bf85781
Session ID: e932a3a8

**Comment by etherunit** [comment]
Thanks guys! We will include this information in our internal doc for manual reimbursements.
