### ISSUE TITLE
Issues with the Mysterium node launcher on Mac

### ISSUE THREAD

**Issue by PeterWan816** [mysteriumnetwork/node#4967]
**Describe the bug**
as I have used the mysterium node launcher to create and install the docker image, I have no control and no idea of what is going on in the background. the ports seem to be exposed but not bounded, thus, no incoming traffic to the docker image was successful.

**To Reproduce**
1. Use the Mysterium node launcher to install the docker and docker image and the node
2. click on the inspect in the Containers/Apps tab of the node image in the Docker application
3. all the configured ports from 42000~42100 are not bounded, unlike the code provided by https://docs.mysterium.network/troubleshooting/troubleshooting-nat-type-related-issues where all the needed ports are bounded and/or forwarded
4. all ping to peer time out, no successful connection

**Expected behavior**
it is supposed to bound everything 

**Screenshots**
![螢幕截圖 2022-04-03 13 54 24](https://user-images.githubusercontent.com/26960902/161413941-becc4ba9-f2e2-4521-9c97-740f3c5a15be.png)

**Environment (please complete the following information):**
 - Node version: 1.6.2-alpine
 - OS: MacOs 12.3 stable
 - Desktop app version (if applicable): 1.0.24(1)
 - Docker (if applicable): 4.6.0(75818); configured by the node launcher
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
honestly, I don't have much idea on why is every ping not delivered. according to the Wireshark and my firewall, everything is passed through as the NAT was set correctly. Yet, all the ping to the peer has resulted in timeout. Also, I was not able to import the identity exported from the launcher image. it always said error (Bad Request (http://127.0.0.1:4050/identities-import). Possible error: failed to import identity: invalid character 'a' looking for beginning of object key string). i was not able to configure any new node on my network either, with error ( server response invalid: 403 Forbidden (https://pilvytis.mysterium.network/api/v2/payment/cardinity/orders){"error":"payments are disabled"} (path="/v2/identities/0xee39b75ed90f305c030dc7af7db14a669998e810/cardinity/payment-order”) )

**Comment by Zensey** [comment]
Hi @PeterWan816 
Thanks for your detailed bug report.

Please try this build:
https://github.com/mysteriumnetwork/myst-launcher-osx/releases/download/1.0.28-rc2/mysterium_launcher_macos.dmg

With this build UDP ports should be bound, but you'll have to re-apply port-forwarding mode.

**Comment by etherunit** [comment]
@PeterWan816 Any updates?

**Comment by PeterWan816** [comment]
Hello,

I was busy lately, that is why I just saw this email today. I will try this update ASAP and will let you know if it is fixed. 

Thank you!

Best,
Peter Wan

**Comment by Zensey** [comment]
@PeterWan816 
note, there was a bug in rc2, so please try another build:
https://github.com/mysteriumnetwork/myst-launcher-osx/releases/tag/1.0.28-rc3

**Comment by PeterWan816** [comment]
the node can be connected from the mysterium network tester now, just that the Web UI cannot be connected. it was initially a bad credential error, then I go ahead and reset it using the "myst reset" command, and now, I cannot connect to the web UI  X_X my browser said cannot connect to *IP address* but I am remotely controlling the unit on my computer and the other services running on that unit is working just fine, I did not get where did the error come from.

**Comment by Zensey** [comment]
@PeterWan816 
an issue with web UI has been fixed in latest build
https://github.com/mysteriumnetwork/myst-launcher-osx/releases/tag/1.0.28-rc3

**Comment by Zensey** [comment]
@PeterWan816 
please try the latest version
https://github.com/mysteriumnetwork/myst-launcher-osx/releases/tag/1.0.30

**Comment by PeterWan816** [comment]
Well, I have installed the latest version. I tried removing the previous node launcher then install it from the pre-release version but the Web UI is still not working (at least for me). It is wried. I have used nmap to check and see if the port is opened and it saids :
Host is up (1.0s latency).

PORT     STATE  SERVICE
4449/tcp closed privatewire

So… maybe it is not fixed? Or somethings else have to do with this, cause localhost does not work either.
Thanks!
