### ISSUE TITLE
All stats missing

### ISSUE THREAD

**Issue by arnav7633** [mysteriumnetwork/node#5071]
After a few hours of the new update on accessing the dashboard everything is shown as 0 and the node is shown os offline but its listed online on online UI and no errors in the logs as far as i can tell
I am using the raspi os lite and node version1.6.5
![image](https://user-images.githubusercontent.com/68459855/165876176-0726a5c0-94e3-489d-a3c8-d360ba9ac0d2.png)
![image](https://user-images.githubusercontent.com/68459855/165876186-6c3c40e6-1a52-4db0-8c7a-deba6a68e510.png)
![image](https://user-images.githubusercontent.com/68459855/165876240-72e16ef4-1f42-4e32-b0ea-5acf503d8c7b.png)

**Comment by arnav7633** [comment]
Alright I will when this occurs again. Do note it needs a restart to fix it

**Comment by Peter-SovietSquirrel** [comment]
[node_log.zip](https://github.com/mysteriumnetwork/node/files/8590558/node_log.zip)
> If you could submit node logs for around the time this happened, that'd be great.

> 
Here are logs for a node that also had the same issue at around the same time, also same node version.

**Comment by arnav7633** [comment]
It happened again. How do I make the log zip file?

**Comment by Peter-SovietSquirrel** [comment]
> It happened again. How do I make the log zip file?

You can output the log using the command below or when you restart the service on the NodeUi click the bug report button at the bottom left and in extra information include github#5071

`sudo journalctl -u mysterium-node.service > node.logs`

**Comment by isaackielma** [comment]
https://mystnodes.com/support/logs/2022-04-29-e6459ed8-5516-42b2-9155-a202b0f45988-mysterium-node.zip3386183430

**Comment by tomasmik** [comment]
Update to latest node version. Should be fixed in version 1.6.8.

**Comment by Peter-SovietSquirrel** [comment]
[nodes.zip](https://github.com/mysteriumnetwork/node/files/8647922/nodes.zip)

Issue is still present in 1.6.9
