### ISSUE TITLE
Node shows the status "Connection failed" on mystnodes, but works fine

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5185]
Logs:

https://mystnodes.com/support/logs/2022-06-13-677ebf97-4080-49e6-9250-d5c4f030e841-mysterium-node.zip1551875586

<img width="985" alt="Screenshot 2022-06-13 at 19 29 56" src="https://user-images.githubusercontent.com/84313603/173458321-e17586b0-42ca-4f75-a8ae-2548ccb3c22a.png">

**Comment by etherunit** [comment]
@isaackielma Ask him to check it now. It was fixed.

**Comment by djcrawleravp** [comment]
Still happening to m
<img width="483" alt="Screen Shot 2022-06-15 at 17 27 42" src="https://user-images.githubusercontent.com/12896341/173932994-9acc9098-767a-49cc-b954-8cdb9c33c287.png">
e

**Comment by Jbt8** [comment]
Still having issues with Mysterium node running on Controllino hotspot. I've tried every setting I could find and still connection failure. The node initially was on line for the first few days, then went to Connection failure. I've opened a ticket with Controllino support, as Mysterium does not provide support for a node running on this hotspot maker.

**Comment by djcrawleravp** [comment]
still the same, now just one node is working
