### ISSUE TITLE
Time outs when opening node web pages

### ISSUE THREAD

**Issue by DavidR000** [mysteriumnetwork/node#5287]
**Describe the bug**
I am running mysterium node in docker  under an ubuntu virtual machine.
This was running OK and then a number of weeks back I stopped seeing any usage and I see timeouts reported when trying to open the node dashboard and related pages.  I have updated the docker image several times now but it Is still the same.

All required external ports are forwarded to the ip address of the virtual machine.

**To Reproduce**
1. Log into the node (I.e. http://192.168.1.78:4449/#/dashboard)
2. the web pages displays but with a spining arrow then eventually displays the page but also a timout error message.
The node does show online after this but never sees any traffic.

Navigating to other pages on the dash board have a similar effect.

**Expected behavior**
We should be able to launch the dashboard an dgo straight into it without this delay and would expect to see some traffic being passed.

**Screenshots**
See attached
![Screenshot_20220704-171041_Chrome](https://user-images.githubusercontent.com/44427133/177772864-61e6f00b-9eaa-4224-9e25-3cda2f77c174.jpg)

![Screenshot_20220704-171030_Chrome](https://user-images.githubusercontent.com/44427133/177772980-e7ab3dd4-30f0-48b0-bf25-fc70874c07fc.jpg)

**Environment (please complete the following information):**
 - Node version: 1.17.1
 - OS:  ubuntu (running as a virtual machine on a Synology NAS)
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker running under the  ubuntu virtual machine
 - 
 - Your identity 
0x6f26116ce1a280abb0117e96a68db99ad2baae65

 - Payment (top-op) reference

**Additional context**

**Comment by etherunit** [comment]
@DavidR000 Apologies for a delayed reply. Do you still experience this issue?

**Comment by DavidR000** [comment]
Hi, Yes I am still having issues

**Comment by etherunit** [comment]
Hi @DavidR000.
This issue should be fixed already.
Please update your node to the latest version to fix it

**Comment by DavidR000** [comment]
Hi,
I have updated to the latest version and the issue remains the same.
