### ISSUE TITLE
Same IP address assigned to different myst interfaces

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#5508]
**Describe the bug**
When 2 or more clients are connected, the same IP address is being assigned to different myst interfaces.

**To Reproduce**
Wait for 2 or more clients to be connected
Issue "ifconfig" command

**Expected behavior**
I would expect that each client is connected to an interface with different IP address

**Screenshots**
![image](https://user-images.githubusercontent.com/34000198/193798204-22af53b5-647d-40ae-86a8-493115d65350.png)

**Environment (please complete the following information):**
 - Node version: 1.17.5
 - OS: Mystberry
 - Your identity: 0x4e29980147340362e66c58474ec2b2d79648d0c4

**Additional context**
Log attached:
[myst.log](https://github.com/mysteriumnetwork/node/files/9705078/myst.log)

**Comment by lollapalooza1973** [comment]
And again
![image](https://user-images.githubusercontent.com/34000198/193804363-e4432ff7-252d-4534-a894-a6f2f379ed79.png)

**Comment by lollapalooza1973** [comment]
It happens very often:
![image](https://user-images.githubusercontent.com/34000198/193820589-c7761bbd-6c3a-4864-8a27-2f140cd9d2e6.png)

**Comment by soffokl** [comment]
@lollapalooza1973 please try to update to the 1.18.1 version, it should resolve the problem.

**Comment by lollapalooza1973** [comment]
@soffokl I have updated, but I'm still experiencing the issue
![image](https://user-images.githubusercontent.com/34000198/194034317-0bd0c604-b4e9-41a3-9d6a-b8cad8b86a63.png)

**Comment by lollapalooza1973** [comment]
@soffokl Here's the log, I hope it's useful
[myst.log](https://github.com/mysteriumnetwork/node/files/9714677/myst.log)

**Comment by soffokl** [comment]
@lollapalooza1973 there was another fix released in 1.18.2, could you please try that version?

**Comment by lollapalooza1973** [comment]
@soffokl it's not available yet with apt update

**Comment by soffokl** [comment]
@lollapalooza1973 yep, sorry, the build is still in progress and it will take a few more minutes to finish it.

**Comment by etherunit** [comment]
@lollapalooza1973 Please try now

**Comment by rmtucker** [comment]
![image](https://user-images.githubusercontent.com/6954079/194053711-5134b9b2-9356-4960-92ce-1a6ec953fcfd.png)
Problem still there using 1.18.2

**Comment by lollapalooza1973** [comment]
@etherunit Updated to 1.18.2, still facing the same issue with duplicated IP address.
Screenshot below and log attached (I have collected the logs after a couple of attempts from the client).
![image](https://user-images.githubusercontent.com/34000198/194057728-43155aa6-f196-4fdb-a818-2da10ffbc43e.png)
[myst.log](https://github.com/mysteriumnetwork/node/files/9715464/myst.log)

**Comment by etherunit** [comment]
Please update to 1.18.3
It should work

**Comment by lollapalooza1973** [comment]
It seems to be working fine now.
